experiment:
  name: "pancreatic_cancer_guidelines"
  version: "3"
  output_dir: "output_files/25"

input_files:
  problem_text: "input_files/pancreatic_cancer_guidelines.txt"
  constant_prompt: "input_files/constant_prompt.txt"
  predicate_prompt: "input_files/predicate_prompt.txt"
  rule_generation_prompt: "input_files/rule_generation_2_prompt.txt"
  verify_rules_prompt: "input_files/check_outputs.txt"
  ground_truth: "input_files/ground_truth3.lp"
  zero_shot: "input_files/zero_shot.txt"
  

llm_params:
  constant_inference_iterations: 0
  predicate_inference_iterations: 0
  rule_generation_iterations: 0
  verify_rules_iterations: 0
  model: "claude-3-7-sonnet-20250219"
  temperature: 0.0001
